variables:
  UV_VERSION: "0.5"
  BASE_LAYER: bookworm-slim
  # GitLab CI creates a separate mountpoint for the build directory,
  # so we need to copy instead of using hard links.
  UV_LINK_MODE: copy

stages:          # List of stages for jobs, and their order of execution
  - test

unit-test:   # This job runs in the test stage.
  stage: test
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    key:
      files:
        - uv.lock # Recreate the cache if the lock file changes
      prefix: $CI_COMMIT_REF_SLUG-$PYTHON_VERSION
    paths:
      - .uv-cache/ # Cache the uv global cache directory
  before_script:
    # Set uv cache directory to be inside the project to allow caching
    - export UV_CACHE_DIR=$CI_PROJECT_DIR/.uv-cache
    - uv venv --seed # Create a virtual environment for the project
    - . .venv/bin/activate
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.10", "3.11", "3.12", "3.13"]   
  script:
    - uv sync --all-groups
    - uv run pytest
  after_script:
    - uv cache prune --ci # Trim the cache to optimize for CI

#lint-test-job:   # This job also runs in the test stage.
#  stage: test    # It can run at the same time as unit-test-job (in parallel).
#  script:
#    - echo "Linting code... This will take about 10 seconds."
#    - sleep 10
#    - echo "No lint issues found."
#
#deploy-job:      # This job runs in the deploy stage.
#  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
