[build-system]
requires = ["setuptools >= 80.0.0", "setuptools_scm>=8.0", "cython>=3.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "memory.fm"
dynamic = ["version"]
dependencies = [
    "sqlalchemy>=2.0.48",
]
requires-python = ">=3.10"
authors = [
	{name="Siddhant Sharma", email="sharmasiddhant@protonmail.com" },
]
description = "A small Python library and CLI tool for reading, analyzing, visualizing and exporting Last.fm scrobble data."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["lastfm", "last.fm", "music", "dataset", "data analysis", "dashboard", "scrobble"]
classifiers = [
"Development Status :: 3 - Alpha",
"Intended Audience :: End Users/Desktop",
"Intended Audience :: Developers",
"Topic :: Scientific/Engineering :: Information Analysis",
"Topic :: Software Development :: Libraries :: Python Modules",
"Topic :: Software Development :: User Interfaces",
"Topic :: Internet",
"Topic :: Documentation :: Sphinx",
]

[tool.setuptools_scm]
local_scheme="no-local-version"
fallback_version = "0.0.0"

[project.optional-dependencies]
dev = [
    "importlib-metadata>=9.0.0",
    "ipython>=8.39.0",
    "mypy>=1.20.0",
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
    "ruff>=0.15.8",
]
doc = [
    "pydata-sphinx-theme>=0.16.1",
    "sphinx==7.4.7",
    "sphinx-autodoc-typehints>=2.3.0",
    "sphinx-design>=0.6.1",
    "sphinx-sqlalchemy>=0.3.0",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Repository = "https://github.com/shsiddhant/memory.fm"
Issues = "https://github.com/shsiddhant/memory.fm/issues"
Changelog = "https://github.com/shsiddhant/memory.fm/blob/main/CHANGELOG.md"

[tool.ruff]
line-length = 88
target-version = "py310"

[tool.ruff.format]
# Enable reformatting of code snippets in docstrings.
docstring-code-format = true

[tool.ruff.lint]

select = [
  # pyflakes
  "F",
  # pycodestyle
  "E", "W",
  # flake8-2020
  "YTT",
  # flake8-bugbear
  "B",
  # flake8-quotes
  "Q",
  # flake8-debugger
  "T10",
  # flake8-gettext
  "INT",
  # pylint
  "PL",
  # misc lints
  "PIE",
  # flake8-pyi
  "PYI",
  # tidy imports
  "TID",
  # implicit string concatenation
  "ISC",
  # type-checking imports
  "TCH",
  # comprehensions
  "C4",
  # pygrep-hooks
  "PGH",
  # Ruff-specific rules
  "RUF",
  # flake8-bandit: exec-builtin
  "S102",
  # numpy-legacy-random
  "NPY002",
  # Perflint
  "PERF",
  # flynt
  "FLY",
  # flake8-logging-format
  "G",
  # flake8-future-annotations
  "FA",
]

ignore = [
  ### Intentionally disabled
  # space before : (needed for how black formats slicing)
  "E203",
  # module level import not at top of file
  "E402",
  # do not assign a lambda expression, use a def
  "E731",
  # line break before binary operator
  # "W503",  # not yet implemented
  # line break after binary operator
  # "W504",  # not yet implemented
  # controversial
  "B006",
  # controversial
  "B007",
  # controversial
  "B008",
  # setattr is used to side-step mypy
  "B009",
  # getattr is used to side-step mypy
  "B010",
  # tests use assert False
  "B011",
  # tests use comparisons but not their returned value
  "B015",
  # false positives
  "B019",
  # Loop control variable overrides iterable it iterates
  "B020",
  # Function definition does not bind loop variable
  "B023",
  # Functions defined inside a loop must not use variables redefined in the loop
  # "B301",  # not yet implemented
  # Only works with python >=3.10
  "B905",
  # Too many arguments to function call
  "PLR0913",
  # Too many returns
  "PLR0911",
  # Too many branches
  "PLR0912",
  # Too many statements
  "PLR0915",
  # Redefined loop name
  "PLW2901",
  # Global statements are discouraged
  "PLW0603",
  # Docstrings should not be included in stubs
  "PYI021",
  # Use `typing.NamedTuple` instead of `collections.namedtuple`
  "PYI024",
  # No builtin `eval()` allowed
  "S307",
  # compare-to-empty-string
  "PLC1901",
  # while int | float can be shortened to float, the former is more explicit
  "PYI041",
  # incorrect-dict-iterator, flags valid Series.items usage
  "PERF102",
  # try-except-in-loop, becomes useless in Python 3.11
  "PERF203",


  ### TODO: Enable gradually
  # Useless statement
  "B018",
  # Within an except clause, raise exceptions with ...
  "B904",
  # Magic number
  "PLR2004",
  # comparison-with-itself
  "PLR0124",
  # Consider `elif` instead of `else` then `if` to remove indentation level
  "PLR5501",
  # collection-literal-concatenation
  "RUF005",
  # pairwise-over-zipped (>=PY310 only)
  "RUF007",
  # explicit-f-string-type-conversion
  "RUF010",
  # mutable-class-default
  "RUF012"
]

exclude = [
  "doc/sphinxext/*.py",
  "doc/build/*.py",
  "doc/temp/*.py",
  ".eggs/*.py",
]
