[build-system]
requires = ["setuptools >= 80.0.0", "setuptools_scm>=8.0"]
build-backend = "setuptools.build_meta"

[project]
name = "memory.fm"
dynamic = ["version"]
dependencies = [
	"pandas>=2.3.3,<3.0",
	"tabulate>=0.9,<1.0",
	"pyyaml>=6.0,<7.0",
	"typer>=0.19,<1.0",
	"rich>=14.1,<15.0",
	"pyarrow>=21.0,<22.0",
	"wcwidth>=0.2.14,<0.3",
	"platformdirs>=4.4.0",
]
requires-python = ">=3.10"
authors = [
	{name="Siddhant Sharma", email="sharmasiddhant@protonmail.com" },
]
description = "A small Python library and CLI tool for reading, analyzing, visualizing and exporting Last.fm scrobble data."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["lastfm", "last.fm", "music", "dataset", "data nalysis"]
classifiers = [
"Development Status :: 2 - Pre-Alpha",
"Intended Audience :: End Users/Desktop",
"Intended Audience :: Developers",
"Topic :: Software Development :: Libraries :: Python Modules",
"Topic :: Internet :: Log Analysis",
]

[tool.setuptools_scm]
# version_scheme = "no-guess-dev"
local_scheme="no-local-version"
fallback_version = "0.0.0"

[project.optional-dependencies]
dev = [
    "pytest",
    "python-lsp-ruff",
		"tzlocal",
]
doc = [
		"sphinx",
		"sphinx_design",
		"pydata-sphinx-theme",
		"numpydoc",
		"ipython>=8.37.0",
]
timezone = [
	"tzlocal",
]

[project.scripts]
memoryfm = "memoryfm.cli.main:app"

[tool.setuptools.packages.find]
where = ["src"]

[project.urls]
Repository = "https://gitlab.com/sharmasiddhant/memory.fm.git"
Issues = "https://gitlab.com/sharmasiddhant/memory.fm/-/issues"
Changelog = "https://gitlab.com/sharmasiddhant/memory.fm/-/blob/main/CHANGELOG.md"
