"""add album, artist, track tables and use track id in scrobbles.

Revision ID: e1fef182da4c
Revises: 792cbc163ac4
Create Date: 2026-04-28 12:38:24.530871

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e1fef182da4c"
down_revision: Union[str, Sequence[str], None] = "792cbc163ac4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "albums",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "artist_id"),
    )
    op.create_index(op.f("ix_albums_artist_id"), "albums", ["artist_id"], unique=False)
    op.create_table(
        "tracks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("album_id", sa.Integer(), nullable=False),
        sa.Column("artist_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["album_id"],
            ["albums.id"],
        ),
        sa.ForeignKeyConstraint(
            ["artist_id"],
            ["artists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "album_id"),
    )
    op.create_index(op.f("ix_tracks_album_id"), "tracks", ["album_id"], unique=False)
    op.create_index(op.f("ix_tracks_artist_id"), "tracks", ["artist_id"], unique=False)
    op.add_column("scrobbles", sa.Column("track_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        op.f("scrobbles_timestamp_track_artist_album_user_id_key"),
        "scrobbles",
        type_="unique",
    )
    op.create_index(
        op.f("ix_scrobbles_track_id"), "scrobbles", ["track_id"], unique=False
    )
    op.create_unique_constraint(None, "scrobbles", ["timestamp", "track_id", "user_id"])
    op.create_foreign_key(None, "scrobbles", "tracks", ["track_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "scrobbles", type_="foreignkey")
    op.drop_constraint(None, "scrobbles", type_="unique")
    op.drop_index(op.f("ix_scrobbles_track_id"), table_name="scrobbles")
    op.create_unique_constraint(
        op.f("scrobbles_timestamp_track_artist_album_user_id_key"),
        "scrobbles",
        ["timestamp", "track", "artist", "album", "user_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("scrobbles", "track_id")
    op.drop_index(op.f("ix_tracks_artist_id"), table_name="tracks")
    op.drop_index(op.f("ix_tracks_album_id"), table_name="tracks")
    op.drop_table("tracks")
    op.drop_index(op.f("ix_albums_artist_id"), table_name="albums")
    op.drop_table("albums")
    op.drop_table("artists")
    # ### end Alembic commands ###
